/*
 * WranglerForm.Designer.cs - Form Layout
 * =======================================
 *
 * PURPOSE:
 * This file contains the Windows Forms designer-generated code for the UI layout.
 * It defines all controls, their positions, sizes, and basic properties.
 *
 * LAYOUT STRUCTURE:
 * +-------------------------------------------+
 * |  [Title: TheWrangler]                     |
 * +-------------------------------------------+
 * |  Selected File: [filename display]        |
 * |  [Browse...]                              |
 * +-------------------------------------------+
 * |  [ ] Ignore Home                          |
 * +-------------------------------------------+
 * |  [    RUN    ]    [Stop Gently]           |
 * +-------------------------------------------+
 * |  Status: Ready                            |
 * +-------------------------------------------+
 * |  +---------------------------------------+|
 * |  |  Log output area                      ||
 * |  |  (RichTextBox with scrolling)         ||
 * |  +---------------------------------------+|
 * +-------------------------------------------+
 *
 * NOTES FOR CLAUDE:
 * - This file is typically auto-generated by Visual Studio
 * - Manual edits are fine but be careful with region structure
 * - All controls are defined in InitializeComponent()
 * - Colors/styling are applied in WranglerForm.cs after init
 */

namespace TheWrangler
{
    partial class WranglerForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - defines all UI controls.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnlMain = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblSelectedFile = new System.Windows.Forms.Label();
            this.lblFilePath = new System.Windows.Forms.Label();
            this.btnBrowse = new System.Windows.Forms.Button();
            this.chkIgnoreHome = new System.Windows.Forms.CheckBox();
            this.lblRemotePort = new System.Windows.Forms.Label();
            this.txtRemotePort = new System.Windows.Forms.TextBox();
            this.lblServerStatus = new System.Windows.Forms.Label();
            this.btnRun = new System.Windows.Forms.Button();
            this.btnStopGently = new System.Windows.Forms.Button();
            this.lblStatus = new System.Windows.Forms.Label();
            this.txtLog = new System.Windows.Forms.RichTextBox();
            this.pnlMain.SuspendLayout();
            this.SuspendLayout();

            //
            // pnlMain - Main container panel
            //
            this.pnlMain.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlMain.Controls.Add(this.lblTitle);
            this.pnlMain.Controls.Add(this.lblSelectedFile);
            this.pnlMain.Controls.Add(this.lblFilePath);
            this.pnlMain.Controls.Add(this.btnBrowse);
            this.pnlMain.Controls.Add(this.chkIgnoreHome);
            this.pnlMain.Controls.Add(this.lblRemotePort);
            this.pnlMain.Controls.Add(this.txtRemotePort);
            this.pnlMain.Controls.Add(this.lblServerStatus);
            this.pnlMain.Controls.Add(this.btnRun);
            this.pnlMain.Controls.Add(this.btnStopGently);
            this.pnlMain.Controls.Add(this.lblStatus);
            this.pnlMain.Controls.Add(this.txtLog);
            this.pnlMain.Location = new System.Drawing.Point(12, 12);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Padding = new System.Windows.Forms.Padding(15);
            this.pnlMain.Size = new System.Drawing.Size(460, 437);
            this.pnlMain.TabIndex = 0;

            //
            // lblTitle - Main title label
            //
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.Location = new System.Drawing.Point(15, 15);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(168, 32);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "TheWrangler";

            //
            // lblSelectedFile - "Selected File:" label
            //
            this.lblSelectedFile.AutoSize = true;
            this.lblSelectedFile.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSelectedFile.Location = new System.Drawing.Point(17, 65);
            this.lblSelectedFile.Name = "lblSelectedFile";
            this.lblSelectedFile.Size = new System.Drawing.Size(87, 19);
            this.lblSelectedFile.TabIndex = 1;
            this.lblSelectedFile.Text = "Selected File:";

            //
            // lblFilePath - Shows selected filename
            //
            this.lblFilePath.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblFilePath.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFilePath.Location = new System.Drawing.Point(17, 87);
            this.lblFilePath.Name = "lblFilePath";
            this.lblFilePath.Size = new System.Drawing.Size(320, 23);
            this.lblFilePath.TabIndex = 2;
            this.lblFilePath.Text = "No file selected";

            //
            // btnBrowse - Browse button
            //
            this.btnBrowse.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBrowse.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBrowse.Location = new System.Drawing.Point(343, 75);
            this.btnBrowse.Name = "btnBrowse";
            this.btnBrowse.Size = new System.Drawing.Size(100, 35);
            this.btnBrowse.TabIndex = 3;
            this.btnBrowse.Text = "Browse...";
            this.btnBrowse.UseVisualStyleBackColor = true;
            this.btnBrowse.Click += new System.EventHandler(this.btnBrowse_Click);

            //
            // chkIgnoreHome - Ignore home checkbox
            //
            this.chkIgnoreHome.AutoSize = true;
            this.chkIgnoreHome.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chkIgnoreHome.Location = new System.Drawing.Point(20, 125);
            this.chkIgnoreHome.Name = "chkIgnoreHome";
            this.chkIgnoreHome.Size = new System.Drawing.Size(268, 23);
            this.chkIgnoreHome.TabIndex = 4;
            this.chkIgnoreHome.Text = "Ignore Home (stay at crafting location)";
            this.chkIgnoreHome.UseVisualStyleBackColor = true;
            this.chkIgnoreHome.CheckedChanged += new System.EventHandler(this.chkIgnoreHome_CheckedChanged);

            //
            // lblRemotePort - Remote port label
            //
            this.lblRemotePort.AutoSize = true;
            this.lblRemotePort.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRemotePort.Location = new System.Drawing.Point(17, 155);
            this.lblRemotePort.Name = "lblRemotePort";
            this.lblRemotePort.Size = new System.Drawing.Size(88, 19);
            this.lblRemotePort.TabIndex = 10;
            this.lblRemotePort.Text = "Remote Port:";

            //
            // txtRemotePort - Remote port text box
            //
            this.txtRemotePort.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRemotePort.Location = new System.Drawing.Point(115, 152);
            this.txtRemotePort.Name = "txtRemotePort";
            this.txtRemotePort.Size = new System.Drawing.Size(70, 25);
            this.txtRemotePort.TabIndex = 11;
            this.txtRemotePort.Text = "7800";
            this.txtRemotePort.Leave += new System.EventHandler(this.txtRemotePort_Leave);

            //
            // lblServerStatus - Server status indicator
            //
            this.lblServerStatus.AutoSize = true;
            this.lblServerStatus.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblServerStatus.Location = new System.Drawing.Point(195, 157);
            this.lblServerStatus.Name = "lblServerStatus";
            this.lblServerStatus.Size = new System.Drawing.Size(95, 15);
            this.lblServerStatus.TabIndex = 12;
            this.lblServerStatus.Text = "Server: Stopped";

            //
            // btnRun - Main run button
            //
            this.btnRun.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRun.Enabled = false;
            this.btnRun.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRun.Location = new System.Drawing.Point(20, 190);
            this.btnRun.Name = "btnRun";
            this.btnRun.Size = new System.Drawing.Size(280, 50);
            this.btnRun.TabIndex = 5;
            this.btnRun.Text = "Run";
            this.btnRun.UseVisualStyleBackColor = true;
            this.btnRun.Click += new System.EventHandler(this.btnRun_Click);

            //
            // btnStopGently - Stop Gently button
            //
            this.btnStopGently.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnStopGently.Enabled = false;
            this.btnStopGently.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStopGently.Location = new System.Drawing.Point(310, 190);
            this.btnStopGently.Name = "btnStopGently";
            this.btnStopGently.Size = new System.Drawing.Size(133, 50);
            this.btnStopGently.TabIndex = 6;
            this.btnStopGently.Text = "Stop Gently";
            this.btnStopGently.UseVisualStyleBackColor = true;
            this.btnStopGently.Click += new System.EventHandler(this.btnStopGently_Click);

            //
            // lblStatus - Status display label
            //
            this.lblStatus.AutoSize = true;
            this.lblStatus.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblStatus.Location = new System.Drawing.Point(17, 250);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(79, 15);
            this.lblStatus.TabIndex = 6;
            this.lblStatus.Text = "Status: Ready";

            //
            // txtLog - Log output area
            //
            this.txtLog.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtLog.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLog.Location = new System.Drawing.Point(20, 275);
            this.txtLog.Name = "txtLog";
            this.txtLog.ReadOnly = true;
            this.txtLog.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Vertical;
            this.txtLog.Size = new System.Drawing.Size(423, 145);
            this.txtLog.TabIndex = 7;
            this.txtLog.Text = "";

            //
            // WranglerForm - Main form
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(484, 461);
            this.Controls.Add(this.pnlMain);
            this.MinimumSize = new System.Drawing.Size(400, 400);
            this.Name = "WranglerForm";
            this.Text = "TheWrangler";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.WranglerForm_FormClosing);
            this.pnlMain.ResumeLayout(false);
            this.pnlMain.PerformLayout();
            this.ResumeLayout(false);
        }

        #endregion

        // Control declarations
        private System.Windows.Forms.Panel pnlMain;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblSelectedFile;
        private System.Windows.Forms.Label lblFilePath;
        private System.Windows.Forms.Button btnBrowse;
        private System.Windows.Forms.CheckBox chkIgnoreHome;
        private System.Windows.Forms.Label lblRemotePort;
        private System.Windows.Forms.TextBox txtRemotePort;
        private System.Windows.Forms.Label lblServerStatus;
        private System.Windows.Forms.Button btnRun;
        private System.Windows.Forms.Button btnStopGently;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.RichTextBox txtLog;
    }
}
